name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.12.1'

    - name: Make Gradle wrapper executable
      run: sudo chmod +x ./gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew build -x test

      # AWS IAM Access
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # Login ECR
    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region us-east-1 \
        | docker login --username AWS --password-stdin ${{ secrets.ECR_URI }}

    # Docker Build
    - name: Build Docker image
      run: docker build -t business-server:latest .

    # Tag For ECR
    - name: Tag Docker image
      run: docker tag business-server:latest ${{ secrets.ERC_REPOSITORY_URI }}

    # ECR Push
    - name: Push to ECR
      run: docker push ${{ secrets.ERC_REPOSITORY_URI }}
